apiVersion: batch/v1
kind: Job
metadata:
  name: database-migration-alt
  namespace: routeclouds-ns
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: migration
        image: awsfreetier30/routeclouds-backend:latest
        imagePullPolicy: Always
        command: ["node"]
        args: ["-e", "require('child_process').execSync('npm run migrate && npm run seed', {stdio: 'inherit'})"]
        envFrom:
        - secretRef:
            name: db-secrets
        - configMapRef:
            name: app-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      restartPolicy: Never
      activeDeadlineSeconds: 300
  backoffLimit: 3
