cat > migration_job.yaml << 'EOF'
apiVersion: batch/v1
kind: Job
metadata:
  name: database-migration
  namespace: routeclouds-ns
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: migration
        image: livingdevopswithakhilesh/devopsdozo:backend-latest
        imagePullPolicy: Always
        command: ["/bin/bash", "-c"]
        args:
        - |
          export FLASK_APP=run.py
          echo "Running database migrations with fresh initialization..."
          
          # Remove existing migrations directory if it exists
          rm -rf migrations
          
          # Initialize fresh migrations
          flask db init
          
          # Create and apply initial migration
          flask db migrate -m "Initial migration"
          flask db upgrade
          
          # Run seed data if needed
          echo "Checking if seed data is needed..."
          python seed_data.py
          
          echo "Database setup completed successfully!"
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: DATABASE_URL
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: SECRET_KEY
        - name: FLASK_APP
          value: "run.py"
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: DB_NAME
        - name: FLASK_DEBUG
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: FLASK_DEBUG
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: DB_PASSWORD
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      restartPolicy: Never
      activeDeadlineSeconds: 300
  backoffLimit: 3
EOF
